services:
  redis:
    command: 'redis-server --requirepass redis'
    container_name: xiveventbuddy-redis
    image: 'redis:alpine'
    networks:
      - xiveventbuddy
    ports:
      - '6379:6379'
    restart: always
    logging:
      options:
        max-size: '20m'
        max-file: '3'

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    networks:
      - xiveventbuddy
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xiveventbuddy
    logging:
      options:
        max-size: '20m'
        max-file: '3'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  xiveventbuddy:
    container_name: xiveventbuddy
    build: .
    env_file:
      - .env
      - .env.development.local
    cap_add:
      - SYS_TIME
    environment:
      - NTP_SERVERS=pool.ntp.org
      - TZ="Europe/London"
    image: favware/xiveventbuddy:latest
    logging:
      options:
        max-size: '1g'
        max-file: '3'
    networks:
      - xiveventbuddy
    restart: always
    tty: true

volumes:
  postgres-data:

networks:
  xiveventbuddy:
