name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-deployment.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workspace }}|${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  PublishXIVEventBuddy:
    name: Publish XIVEventBuddy image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push XIVEventBuddy Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: ghcr.io/favware/xiveventbuddy:latest

  UpdateOnServer:
    name: Update running container on server
    runs-on: ubuntu-latest
    needs: PublishXIVEventBuddy
    steps:
      - name: Update container on server
        uses: favware/ssh-remote-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          username: ${{ secrets.SSH_USERNAME }}
          command: ${{ secrets.SSH_COMMAND }}
          silent: true
